// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteImage(arg1:string):Promise<main.DeleteImageResult>;

export function DeleteVideo(arg1:string):Promise<main.DeleteResult>;

export function GetConfig():Promise<main.Config>;

export function GetImageList():Promise<main.ImageListResult>;

export function GetRandomAPI():Promise<string>;

export function GetVideoList():Promise<main.VideoInfo>;

export function OpenBrowser():Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFileOrDir(arg1:string,arg2:boolean):Promise<string>;

export function SelectImageDirectory():Promise<string>;

export function SetConfig(arg1:string,arg2:number,arg3:Array<string>,arg4:Array<string>,arg5:boolean,arg6:boolean):Promise<void>;

export function StartServer():Promise<number>;

export function StopServer():Promise<void>;

export function SwitchVideo(arg1:string,arg2:string):Promise<main.VideoInfo>;
