// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteImage(arg1) {
  return window['go']['main']['App']['DeleteImage'](arg1);
}

export function DeleteVideo(arg1) {
  return window['go']['main']['App']['DeleteVideo'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetImageList() {
  return window['go']['main']['App']['GetImageList']();
}

export function GetRandomAPI() {
  return window['go']['main']['App']['GetRandomAPI']();
}

export function GetVideoList() {
  return window['go']['main']['App']['GetVideoList']();
}

export function OpenBrowser() {
  return window['go']['main']['App']['OpenBrowser']();
}

export function OpenBrowserByType(arg1) {
  return window['go']['main']['App']['OpenBrowserByType'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFileOrDir(arg1, arg2) {
  return window['go']['main']['App']['SelectFileOrDir'](arg1, arg2);
}

export function SelectImageDirectory() {
  return window['go']['main']['App']['SelectImageDirectory']();
}

export function SetConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SetConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function SwitchVideo(arg1, arg2) {
  return window['go']['main']['App']['SwitchVideo'](arg1, arg2);
}
